FROM nvcr.io/nvidia/tritonserver:24.06-py3-igpu

ARG HAILORT_VERSION=4.20
ENV HAILORT_VERSION ${HAILORT_VERSION}

ENV PATH /opt/tritonserver/bin:${PATH}
# Remove once https://github.com/openucx/ucx/pull/9148 is available
# in the min container.
ENV UCX_MEM_EVENTS no

ENV TF_ADJUST_HUE_FUSED         1
ENV TF_ADJUST_SATURATION_FUSED  1
ENV TF_ENABLE_WINOGRAD_NONFUSED 1
ENV TF_AUTOTUNE_THRESHOLD       2
ENV TRITON_SERVER_GPU_ENABLED   0

# Create a user that can be used to run triton as
# non-root. Make sure that this user to given ID 1000. All server
# artifacts copied below are assign to this user.
ENV TRITON_SERVER_USER=triton-server
RUN userdel tensorrt-server > /dev/null 2>&1 || true \
    && if ! id -u $TRITON_SERVER_USER > /dev/null 2>&1 ; then \
    useradd $TRITON_SERVER_USER; \
    fi \
    && [ `id -u $TRITON_SERVER_USER` -eq 1000 ] \
    && [ `id -g $TRITON_SERVER_USER` -eq 1000 ]

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive

# Common dependencies. FIXME (can any of these be conditional? For
# example libcurl only needed for GCS?)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    clang \
    dirmngr \
    gperf \
    libb64-0d \
    libcurl4-openssl-dev \
    libgoogle-perftools-dev \
    libjemalloc-dev \
    libnuma-dev \
    libre2-9 \
    software-properties-common \
    curl \
    git \
    tree \
    wget \
    \
    && rm -rf /var/lib/apt/lists/*

# Set TCMALLOC_RELEASE_RATE for users setting LD_PRELOAD with tcmalloc
ENV TCMALLOC_RELEASE_RATE 200

# python3, python3-pip and some pip installs required for the python backend
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libarchive-dev \
    python3-pip \
    libpython3-dev \
    && pip3 install --upgrade pip \
    && pip3 install --upgrade \
    wheel \
    setuptools \
    # "numpy<2" \
    virtualenv \
    && rm -rf /var/lib/apt/lists/*

# Install hailort
COPY hailo /hailo 
RUN dpkg --install /hailo/deps/arm64/${HAILORT_VERSION}/hailort_${HAILORT_VERSION}.0_arm64.deb || true
RUN pip install --no-cache /hailo/deps/arm64/${HAILORT_VERSION}/hailort-${HAILORT_VERSION}.0-cp310-cp310-linux_aarch64.whl
RUN pip install onnxruntime --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
RUN pip install --no-cache -r /hailo/requirements-arm64.txt
RUN rm -r /hailo