
#
# Multistage build.
#
ARG TRITON_VERSION=2.46.0
ARG TRITON_CONTAINER_VERSION=24.05

FROM tritonserver:latest AS full

FROM ubuntu:22.04

ARG TRITON_VERSION
ARG TRITON_CONTAINER_VERSION

ENV TRITON_SERVER_VERSION ${TRITON_VERSION}
ENV NVIDIA_TRITON_SERVER_VERSION ${TRITON_CONTAINER_VERSION}
LABEL com.nvidia.tritonserver.version="${TRITON_SERVER_VERSION}"

ARG HAILORT_VERSION=4.19
ENV HAILORT_VERSION ${HAILORT_VERSION}

ENV PATH /opt/tritonserver/bin:${PATH}
# Remove once https://github.com/openucx/ucx/pull/9148 is available
# in the min container.
ENV UCX_MEM_EVENTS no

ENV TF_ADJUST_HUE_FUSED         1
ENV TF_ADJUST_SATURATION_FUSED  1
ENV TF_ENABLE_WINOGRAD_NONFUSED 1
ENV TF_AUTOTUNE_THRESHOLD       2
ENV TRITON_SERVER_GPU_ENABLED   0

# Create a user that can be used to run triton as
# non-root. Make sure that this user to given ID 1000. All server
# artifacts copied below are assign to this user.
ENV TRITON_SERVER_USER=triton-server
RUN userdel tensorrt-server > /dev/null 2>&1 || true \
    && if ! id -u $TRITON_SERVER_USER > /dev/null 2>&1 ; then \
    useradd $TRITON_SERVER_USER; \
    fi \
    && [ `id -u $TRITON_SERVER_USER` -eq 1000 ] \
    && [ `id -g $TRITON_SERVER_USER` -eq 1000 ]

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive

# Common dependencies. FIXME (can any of these be conditional? For
# example libcurl only needed for GCS?)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    clang \
    dirmngr \
    gperf \
    libb64-0d \
    libcurl4-openssl-dev \
    libgoogle-perftools-dev \
    libjemalloc-dev \
    libnuma-dev \
    libre2-9 \
    software-properties-common \
    curl \
    git \
    tree \
    wget \
    \
    && rm -rf /var/lib/apt/lists/*

# Set TCMALLOC_RELEASE_RATE for users setting LD_PRELOAD with tcmalloc
ENV TCMALLOC_RELEASE_RATE 200

# install intel igpu drivers
RUN wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
    gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy/lts/2350 unified" | \
    tee /etc/apt/sources.list.d/intel-gpu-jammy.list && apt-get update

RUN apt-get install -y --no-install-recommends \
    ocl-icd-libopencl1 \
    intel-opencl-icd \
    intel-level-zero-gpu \
    level-zero \
    intel-gpu-tools \
    && rm -rf /var/lib/apt/lists/* 

# python3, python3-pip and some pip installs required for the python backend
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libarchive-dev \
    python3-pip \
    libpython3-dev \
    && pip3 install --upgrade pip \
    && pip3 install --upgrade \
    wheel \
    setuptools \
    # "numpy<2" \
    virtualenv \
    && rm -rf /var/lib/apt/lists/*

# Install hailort
COPY hailo /hailo 
RUN dpkg --install /hailo/deps/${HAILORT_VERSION}/hailort_${HAILORT_VERSION}.0_amd64.deb || true
RUN pip install --no-cache /hailo/deps/${HAILORT_VERSION}/hailort-${HAILORT_VERSION}.0-cp310-cp310-linux_x86_64.whl
RUN pip install --no-cache -r /hailo/requirements.txt
RUN rm -r /hailo

WORKDIR /opt/tritonserver
RUN rm -fr /opt/tritonserver/*
ENV NVIDIA_PRODUCT_NAME="Triton Server"
COPY docker/entrypoint.d/ /opt/nvidia/entrypoint.d/

ENV NVIDIA_BUILD_ID 94071063
LABEL com.nvidia.build.id=94071063
LABEL com.nvidia.build.ref=3afe5b28be391b56365693a1e414e14c98d43c7c

WORKDIR /opt/tritonserver
COPY --chown=1000:1000 --from=full /opt/tritonserver/LICENSE .
COPY --chown=1000:1000 --from=full /opt/tritonserver/TRITON_VERSION .
COPY --chown=1000:1000 --from=full /opt/tritonserver/NVIDIA_Deep_Learning_Container_License.pdf .
COPY --chown=1000:1000 --from=full /opt/tritonserver/bin bin/
COPY --chown=1000:1000 --from=full /opt/tritonserver/lib lib/
COPY --chown=1000:1000 --from=full /opt/tritonserver/include include/
# Copying over backends 
COPY --chown=1000:1000 --from=full /opt/tritonserver/backends/onnxruntime /opt/tritonserver/backends/onnxruntime
COPY --chown=1000:1000 --from=full /opt/tritonserver/backends/python /opt/tritonserver/backends/python

# Top-level /opt/tritonserver/backends not copied so need to explicitly set permissions here
RUN chown triton-server:triton-server /opt/tritonserver/backends
#  Copying over repoagents 
#  Copying over caches 

